+incdir+./design
+incdir+./interface
+incdir+./top
+incdir+./top/test
+incdir+./top/test/environment
+incdir+./top/test/environment/apb_agent
+incdir+./top/test/environment/apb_agent/driver
+incdir+./top/test/environment/apb_agent/monitor
+incdir+./top/test/environment/apb_agent/sequencer
+incdir+./top/test/environment/coverage_collector
+incdir+./top/test/environment/scoreboard
cfs_aligner.v
cfs_aligner_core.v
cfs_apb_if.sv
cfs_ctrl.v
cfs_edge_detect.v
cfs_regs.v
cfs_rx_ctrl.v
cfs_synch.v
cfs_synch_fifo.v
cfs_tx_ctrl.v
design.sv
test/cfs_algn_test_base.sv
test/cfs_algn_test_pkg.sv
test/cfs_algn_test_reg_access.sv
test/environment/apb_agent/cfs_apb_agent.sv
test/environment/apb_agent/cfs_apb_agent_config.sv
test/environment/apb_agent/cfs_apb_pkg.sv
test/environment/apb_agent/cfs_apb_types.sv
test/environment/cfs_algn_env.sv
test/environment/cfs_algn_pkg.sv
top.sv
